todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name="login"),
    url(r'^index/', views.Index.as_view(), name="index"),
    url(r'^add/', views.AddView.as_view(), name="add"),
    url(r'^update/', views.update, name="update"),
    url(r'^edit/', views.editView, name="edit"),
    url(r'^delete/', views.delete, name="delete"),
    url(r'^login/', views.LoginView.as_view(), name="login"),
    url(r'^register/', views.RegisterView.as_view(), name="register"),
    url(r'^removeAccount/', views.removeAccount, name="removeAccount"),
]

todolist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls')),
]

todo/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user_name = models.CharField(max_length = 50)
    password = models.CharField(max_length = 50)

    def __str__(self):
        return self.user_name

    def getClass(self):
        return "User"

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_name = models.CharField(max_length = 50)
    priority = models.IntegerField()
    description = models.CharField(max_length = 300)

    def __str__(self):
        return self.task_name

    def getClass(self):
        return "Task"

todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .models import User, Task
from django.core.urlresolvers import reverse
from django.views import generic

# Create your views here.
currentUser = None

class Index(generic.View):
    def get(self, request):
        global currentUser
        tasks = currentUser.task_set.order_by("-priority")
        new_set = list(tasks)
        a = new_set.append(currentUser)
        context = {"tasks": new_set}
        return render(request, 'todo/index.html', context)

class AddView(generic.View):
    def get(self, request):
        context = {'none': None}
        return render(request, 'todo/add.html', context)

    def post(self, request):
        global currentUser
        user = currentUser #User.objects.get(user_name=request.POST["name"])
        task_name = request.POST["task"]
        priority = request.POST["priority"]
        if(len(request.POST["description"])>0):
            description = request.POST["description"]
        else:
            description = ""
        new_task = user.task_set.create(task_name = task_name, priority=priority, description=description)
        # new_task.save()
        return HttpResponseRedirect(reverse("todo:index"))

class LoginView(generic.View):
    def get(self, request):
        return render(request, 'todo/login.html')

    def post(self, request):
        global currentUser
        name = request.POST["name"]
        if(User.objects.filter(user_name=name).exists()):
            user = User.objects.get(user_name = name)
            if(user.password != request.POST["password"]):
                return render(request, "todo/login.html", {"error": "Incorrect password!"})
            user.save()
            currentUser = user
            print(currentUser.user_name)
            return HttpResponseRedirect(reverse("todo:index"))
        else:
            return render(request, "todo/login.html", {"error": "You need to sign up. Click the 'new user' button to get started!"})

class RegisterView(generic.View):
    def get(self, request):
        return render(request, 'todo/register.html')

    def post(self, request):
        global currentUser
        user_name = request.POST["name"]
        password = request.POST["password"]
        print(request.POST["password"], password)
        if(User.objects.filter(user_name=user_name).exists()):
            return render(request, "todo/register.html", {"error":"This user already exists!"})
        elif(request.POST["password"] != request.POST["confirm"]):
            return render(request, "todo/register.html", {"error":"Passwords do not match!"})
        user = User(user_name = user_name, password = password)
        user.save()
        currentUser = user
        return HttpResponseRedirect(reverse("todo:index"))

def removeAccount(request):
    global currentUser
    user = User.objects.get(user_name=currentUser.user_name)
    user.delete()
    currentUser = None
    return HttpResponseRedirect(reverse("todo:login"))

def editView(request):
    global currentUser
    user = currentUser #User.objects.get(user_name = request.POST["name"])
    task = user.task_set.get(task_name = request.POST["task"])
    print(task)
    context={"task" : task}
    return render(request, "todo/edit.html", context)

def update(request):
    global currentUser
    user = currentUser #request.POST["name"]
    task_name = request.POST["task"]
    if(not user.task_set.filter(task_name=task_name).exists()):
        task = user.task_set.get(task_name = request.POST["old_task"])
        if(task_name != task.task_name):
            task.task_name = task_name
        elif(request.POST["priority"] != task.priority):
            task.priority = request.POST["priority"]
        elif(request.POST["description"] != task.description):
            task.description = request.POST["description"]
        task.save()
    return HttpResponseRedirect(reverse("todo:index"))

def delete(request):
    global currentUser
    obj = currentUser.task_set.get(task_name = request.POST["task"])
    obj.delete()
    return HttpResponseRedirect(reverse("todo:index"))

todo/templates/todo/add.html
{% load staticfiles %}
<html>
    <head>
        <link href="{% static 'todo/form.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="form_container">
            <h1>Add a task</h1>
            <a href="{% url 'todo:index' %}">back</a>
            <form action="{% url 'todo:add' %}" method="post">
            {% csrf_token %}
                <input type="text" name="task">
                <br />
                <input type="radio" name="priority" value="1" required>Low
                <input type="radio" name="priority" value="2" required>Medium
                <input type="radio" name="priority" value="3" required>High
                <br />
                <textarea rows="4" cols="50" name="description"></textarea>
                </br />
                <input type="submit" value="Add task">
            </form>
        </div>
    </body>

todo/templates/todo/edit.html
{% load staticfiles %}
<html>
    <head>    
        <link href="{% static 'todo/form.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="form_container">
            <h1>Edit {{ task.task_name }}</h1>
            <a href="{% url 'todo:index' %}">Back</a>
            <br />
            <form method="post" action="{% url 'todo:update' %}">
                {% csrf_token %}
                <input type="text" name="task" value="{{ task.task_name }}">
                <br />
                <input type="hidden" name="old_task" value="{{ task.task_name }}">
                {% if task.priority == 1 %}
                    <input type="radio" name="priority" value="1" checked="checked"><p>Low</p>
                {% else %}
                    <input type="radio" name="priority" value="1"><p>Low</p>
                {% endif %}

                {% if task.priority == 2 %}
                    <input type="radio" name="priority" value="2" checked="checked"><p>Medium</p>
                {% else %}
                    <input type="radio" name="priority" value="2"><p>Medium</p>
                {% endif %}

                {% if task.priority == 3 %}
                    <input type="radio" name="priority" value="3" checked="checked"><p>High</p>
                {% else %}
                    <input type="radio" name="priority" value="3"><p>High</p>
                {% endif %}
                <br />
                <textarea rows="4" cols="50" name="description">{{ task.description }}</textarea>
                <br />
                <input type="submit" value="Update">
            </form>
            <form method="post" action="{% url 'todo:delete' %}" onsubmit="return confirm('Are you sure?');">
                {% csrf_token %}
                <input type="hidden" name="task" value="{{ task.task_name }}">
                <input type="submit" value="Done with this task?">
            </form>
        </div>
    </body>
</html>

todo/templates/todo/index.html
{% load staticfiles %}
<html>
    <head>
        <link href="{% static 'todo/index.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="task-view">
            <h1>Tasks - 
            {% for task in tasks %}
                {% if task.getClass == "User" %}
                    {{ task.user_name }}
                {% endif %}
            {% endfor %}
            </h1>
            <div class="todo">
                <ul>
                    {% for task in tasks %}
                        {% if task.getClass == "Task" %}
                        <li>
                            <div>
                            <form method="post" action="{% url 'todo:edit' %}">
                                {% csrf_token %}
                                <input type="hidden" name="task" value="{{ task.task_name }}">
                                <input type="submit" value="{{ task.task_name }}" class="edit">
                            </form></div>
                            <p class="priority">
                                <!-- {{ task.priority }} -->
                                {% if task.priority == 1 %}
                                    Low
                                {% elif task.priority == 2 %}
                                    Medium
                                {% else%}
                                    High
                                {% endif %} 
                            </p>
                            <p class="description">{{ task.description }}</p>
                        </li>
                        {% endif %}
                    {% endfor %}
                    </form>
                </ul>
            </div>
            <a href="{% url 'todo:add' %}">Add a task</a>
            <br /><br />
            <a href="{% url 'todo:login' %}">Logout</a>
            <br /><br />
            <a href="{% url 'todo:removeAccount' %}" onclick="return confirm('Are you sure?');">Delete Account</a>
        </div>
    </body>
</html>

todo/templates/todo/login.html
{% load staticfiles %}
<html>
    <head>
        <link href="{% static 'todo/form.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="form_container">
            <h1>Taskmaster</h1>
            {% if error %} <p>{{ error }}</p> {% endif %}
            <form action="{% url 'todo:login' %}" method="post">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Enter your name">
                <br />
                <input type="password" name="password" placeholder="Enter your password">
                <br /><br />
                <input type="submit" value="Show me my tasks">
            </form>
            <a href="{% url 'todo:register' %}">New user?</a>
        </div>
    </body>
</html>

todo/templates/todo/register.html
{% load staticfiles %}
<html>
    <head>
        <link href="{% static 'todo/form.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="form_container">
            <h1>Task Manager</h1>
            {% if error %} <p>{{ error }}</p> {% endif %}
            <form action="{% url 'todo:register' %}" method="post">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Enter your name">
                <br />
                <input type="password" name="password" placeholder="Enter your password">
                <br />
                <input type="password" name="confirm" placeholder="Confirm your password">
                <br />
                <input type="submit" value="Start adding tasks">
            </form>
            <a href="{% url 'todo:login' %}">Exit</a>
        </div>
    </body>
</html>